name: kv_storage_service
description: Defines an abstract interface for key-value storage services in Dart.
repository: https://github.com/flutter-news-app-full-source-code/kv-storage-service
publish_to: none

environment:
  sdk: ^3.9.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^10.0.0
